//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RailwayMSDbEntities : DbContext
    {
        public RailwayMSDbEntities()
            : base("name=RailwayMSDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<station> stations { get; set; }
        public virtual DbSet<train> trains { get; set; }
        public virtual DbSet<UserTable> UserTables { get; set; }
        public virtual DbSet<Main_Schedule> Main_Schedule { get; set; }
        public virtual DbSet<Main_Schedule_Details> Main_Schedule_Details { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<Sub_Route> Sub_Route { get; set; }
        public virtual DbSet<DaysList> DaysLists { get; set; }
    }
}
